### ISSUE TITLE
Add a notice on top of /etc/passwd that the playground is sandboxed

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust-playground#626]
The Rust Security Response WG occasionally receives security reports about remote code execution on the playground. Since the playground uses a sandbox to mitigate that, most of the reports are actually not a security vulnerability.

To reduce the workload of the Security Response WG, and to save potential security researchers time, it would be nice to add a comment on top of `/etc/passwd` and `/etc/shadow` like this:

```
# Hello, and thanks for looking into the Rust Playground's security!
#
# This build is running on an unprivileged, sandboxed Docker container with no
# network access, so while you can technically run arbitrary code on the
# Playground you shouldn't be able to do any damage with it.
#
# Nothing is perfect though: if you find a way to escape the sandbox, please
# disclose it following our security policy! You can find the policy at:
#
#    https://www.rust-lang.org/policies/security
#
```

Those two files are often used by security researcher to demonstrate RCEs, so adding the notice on top of those two files should be enough!

**Comment by 0x4ndy** [comment]
Would it make sense to include this change in `rust-playground/compiler/base/Dockerfile`?

**Comment by shepmaster** [comment]
Great question! I think `postinstall.sh` would be a reasonable place as you could then make a little function that takes in the filename as an argument to avoid duplicating the content.

**Comment by 0x4ndy** [comment]
That's my thinking precisely. I've just made a fork, so I could do it and make pull request.

**Comment by 0x4ndy** [comment]
Unfortunately adding the change in the `postinstall.sh` wasn't feasible due to the fact that the script is running as a `playground` user. Therefore, I've created a dedicated script and added it to the Dockerfile. 

The script is fairly generic so that it's possible now to add any text file to any other text file, either on top or on the bottom, based on the arguments passed during the execution (just in case a similar need arie in the future for another use case). 

Here's the commit: 
https://github.com/rust-lang/rust-playground/commit/7824753c7ede8c752042257e1e0878b48a5a924d

Please let me know if that's good enough, I will then make a Pull Request.
