### ISSUE TITLE
Playground responds by 500 error almost everytime when I try to build code

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [rust-lang/rust-playground#910]
I running using this link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021

Request and server response after pressing `Build` or `Run` button:

```
POST /execute HTTP/3
Host: play.rust-lang.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: */*
Accept-Language: en,ru-RU;q=0.8,ru;q=0.5,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021
content-type: application/json
Content-Length: 160
Origin: https://play.rust-lang.org
Alt-Used: play.rust-lang.org
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

[{"channel":"stable","mode":"debug","edition":"2021","crateType":"lib","tests":false,"code":"fn main(){\n    println!(\"Hello world!\");\n}\n","backtrace":false}](https://play.rust-lang.org/execute)
```

```
HTTP/3 500 Internal Server Error
x-amz-cf-id: ynZgIJ8QM6iuMNh7iInB5GQgjxFTWIM8n9F3zaZXeiBtIDkf5hHfMg==
content-type: text/html
content-length: 170
alt-svc: h3=":443"; ma=86400
server: nginx
date: Fri, 17 Mar 2023 11:11:51 GMT
x-cache: Error from cloudfront
via: 1.1 d9a98758c9298742942e003275c97f92.cloudfront.net (CloudFront)
x-amz-cf-pop: OTP50-C1

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by shepmaster** [comment]
Most investigation is occurring in https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/playground.20down. Will post updates here sporadically.

**Comment by shepmaster** [comment]
Events

After initial reports, we [restarted the server](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/playground.20down/near/342516985), although that did not have a long-lived impact.

Further investigation of Nginx's `error.log` showed the message

```
768 worker_connections are not enough
```

I then [increased that limit](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/playground.20down/near/342539325) to 1536 and then to 7680.

Shortly thereafter, a new message occurred

```
socket() failed (24: Too many open files) while connecting to upstream
```

I then [increased the open file descriptor limit](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/playground.20down/near/342562535) for Nginx and the Playground server.

Since then, the service has seemed to stabilize.

---

My current hypothesis...

In 98e599825162dde8e0e4105217371a0cd37530da, I started **re**connecting the WebSocket after it disconnected. Previously, it would just stay disconnected, but now basically every open playground page with a network connection would connect the WebSocket. 

This led to a slow increase of active connections as the new code reached users and caches were cleared:

![](https://rust-lang.zulipchat.com/user_uploads/4715/2zxaT372GH2Ko2g9B7Tu5uR9/image.png)

Once we hit a critical level (presumably 768), new connections to the server could not be made, resulting in random failures — maybe an asset could not be loaded, or maybe the list of crates, etc.

---

I pushed a change to [close the WebSocket](https://github.com/rust-lang/rust-playground/pull/911) after an hour of no messages (no messages are currently sent anyway). This should give a better reflection of how many people are "actively" using the Playground at a given point in time, which is the current reason for the WebSocket.
